
FROM node:latest as build

WORKDIR /usr/local/app

COPY ./ /usr/local/app/

RUN npm install
RUN npm ci

RUN npm run build

# ---
FROM nginx:latest

COPY --from=build /usr/local/app/dist/front-end /usr/share/nginx/html

EXPOSE 80
