FROM node:18

WORKDIR /usr/local/app

RUN npm install -g @angular/cli

COPY . .

RUN npm install

RUN ng build --configuration production

EXPOSE 4100

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4100", "--disable-host-check"]
