
FROM node:14

WORKDIR /usr/local/app

RUN npm install -g @angular/cli

COPY . .

RUN npm install

# RUN ng build --prod

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4100", "--disable-host-check"]
