FROM python:3.11.5-alpine3.18 as backend

WORKDIR /usr/src/app
ENV FLASK_APP=run.py
ENV FLASK_RUN_HOST=0.0.0.0

RUN apk add --no-cache gcc musl-dev linux-headers

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

COPY ./ /usr/src/app/

CMD [ "flask", "run" ]