FROM python:3.11-slim

WORKDIR /usr/src/app

# Copy the requirements.txt file and the Flask app into the image
COPY ./requirements.txt ./
COPY ./run.py ./  
# Assuming run.py is your Flask app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables for Flask
ENV FLASK_APP=run.py
ENV FLASK_ENV=development
ENV FLASK_RUN_HOST=0.0.0.0

# You might not need gunicorn for development, so it's commented out
# RUN pip install gunicorn

EXPOSE 8000

# Command to run the Flask app in development mode
CMD ["flask", "run", "--port=8000"]
