FROM python:3.11.5-alpine3.18

WORKDIR /usr/src/app
ENV FLASK_APP=run.py
ENV FLASK_RUN_HOST=0.0.0.0

COPY . .

# RUN apk add --no-cache gcc musl-dev linux-headers && \
# RUN  pip install --no-cache-dir -r requirements.txt && \
#     apk del gcc musl-dev linux-headers
RUN pip install gunicorn
RUN  pip install --no-cache-dir -r requirements.txt

EXPOSE 8080


CMD [ "gunicorn", "run:app", "-w", "4", "--bind", "0.0.0.0:8080" ]
