// Generated by gencpp from file server_communication_handler/launch_identify_srv.msg
// DO NOT EDIT!


#ifndef SERVER_COMMUNICATION_HANDLER_MESSAGE_LAUNCH_IDENTIFY_SRV_H
#define SERVER_COMMUNICATION_HANDLER_MESSAGE_LAUNCH_IDENTIFY_SRV_H

#include <ros/service_traits.h>


#include <server_communication_handler/launch_identify_srvRequest.h>
#include <server_communication_handler/launch_identify_srvResponse.h>


namespace server_communication_handler
{

struct launch_identify_srv
{

typedef launch_identify_srvRequest Request;
typedef launch_identify_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct launch_identify_srv
} // namespace server_communication_handler


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::server_communication_handler::launch_identify_srv > {
  static const char* value()
  {
    return "2718218ecd3037e7050a0e8416c50c33";
  }

  static const char* value(const ::server_communication_handler::launch_identify_srv&) { return value(); }
};

template<>
struct DataType< ::server_communication_handler::launch_identify_srv > {
  static const char* value()
  {
    return "server_communication_handler/launch_identify_srv";
  }

  static const char* value(const ::server_communication_handler::launch_identify_srv&) { return value(); }
};


// service_traits::MD5Sum< ::server_communication_handler::launch_identify_srvRequest> should match
// service_traits::MD5Sum< ::server_communication_handler::launch_identify_srv >
template<>
struct MD5Sum< ::server_communication_handler::launch_identify_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::server_communication_handler::launch_identify_srv >::value();
  }
  static const char* value(const ::server_communication_handler::launch_identify_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_communication_handler::launch_identify_srvRequest> should match
// service_traits::DataType< ::server_communication_handler::launch_identify_srv >
template<>
struct DataType< ::server_communication_handler::launch_identify_srvRequest>
{
  static const char* value()
  {
    return DataType< ::server_communication_handler::launch_identify_srv >::value();
  }
  static const char* value(const ::server_communication_handler::launch_identify_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::server_communication_handler::launch_identify_srvResponse> should match
// service_traits::MD5Sum< ::server_communication_handler::launch_identify_srv >
template<>
struct MD5Sum< ::server_communication_handler::launch_identify_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::server_communication_handler::launch_identify_srv >::value();
  }
  static const char* value(const ::server_communication_handler::launch_identify_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::server_communication_handler::launch_identify_srvResponse> should match
// service_traits::DataType< ::server_communication_handler::launch_identify_srv >
template<>
struct DataType< ::server_communication_handler::launch_identify_srvResponse>
{
  static const char* value()
  {
    return DataType< ::server_communication_handler::launch_identify_srv >::value();
  }
  static const char* value(const ::server_communication_handler::launch_identify_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVER_COMMUNICATION_HANDLER_MESSAGE_LAUNCH_IDENTIFY_SRV_H
