// Generated by gencpp from file server_communication_handler/launch_identify_srvResponse.msg
// DO NOT EDIT!


#ifndef SERVER_COMMUNICATION_HANDLER_MESSAGE_LAUNCH_IDENTIFY_SRVRESPONSE_H
#define SERVER_COMMUNICATION_HANDLER_MESSAGE_LAUNCH_IDENTIFY_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_communication_handler
{
template <class ContainerAllocator>
struct launch_identify_srvResponse_
{
  typedef launch_identify_srvResponse_<ContainerAllocator> Type;

  launch_identify_srvResponse_()
    {
    }
  launch_identify_srvResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct launch_identify_srvResponse_

typedef ::server_communication_handler::launch_identify_srvResponse_<std::allocator<void> > launch_identify_srvResponse;

typedef boost::shared_ptr< ::server_communication_handler::launch_identify_srvResponse > launch_identify_srvResponsePtr;
typedef boost::shared_ptr< ::server_communication_handler::launch_identify_srvResponse const> launch_identify_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace server_communication_handler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_communication_handler/launch_identify_srvResponse";
  }

  static const char* value(const ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct launch_identify_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::server_communication_handler::launch_identify_srvResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_COMMUNICATION_HANDLER_MESSAGE_LAUNCH_IDENTIFY_SRVRESPONSE_H
