// Generated by gencpp from file server_communication_handler/launch_identify_srvRequest.msg
// DO NOT EDIT!


#ifndef SERVER_COMMUNICATION_HANDLER_MESSAGE_LAUNCH_IDENTIFY_SRVREQUEST_H
#define SERVER_COMMUNICATION_HANDLER_MESSAGE_LAUNCH_IDENTIFY_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace server_communication_handler
{
template <class ContainerAllocator>
struct launch_identify_srvRequest_
{
  typedef launch_identify_srvRequest_<ContainerAllocator> Type;

  launch_identify_srvRequest_()
    : in()  {
    }
  launch_identify_srvRequest_(const ContainerAllocator& _alloc)
    : in(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _in_type;
  _in_type in;





  typedef boost::shared_ptr< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct launch_identify_srvRequest_

typedef ::server_communication_handler::launch_identify_srvRequest_<std::allocator<void> > launch_identify_srvRequest;

typedef boost::shared_ptr< ::server_communication_handler::launch_identify_srvRequest > launch_identify_srvRequestPtr;
typedef boost::shared_ptr< ::server_communication_handler::launch_identify_srvRequest const> launch_identify_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator1> & lhs, const ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.in == rhs.in;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator1> & lhs, const ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace server_communication_handler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2718218ecd3037e7050a0e8416c50c33";
  }

  static const char* value(const ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2718218ecd3037e7ULL;
  static const uint64_t static_value2 = 0x050a0e8416c50c33ULL;
};

template<class ContainerAllocator>
struct DataType< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "server_communication_handler/launch_identify_srvRequest";
  }

  static const char* value(const ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string in\n"
" \n"
;
  }

  static const char* value(const ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.in);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct launch_identify_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::server_communication_handler::launch_identify_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "in: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.in);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVER_COMMUNICATION_HANDLER_MESSAGE_LAUNCH_IDENTIFY_SRVREQUEST_H
