version: '3.8'

services:
  frontend-service:
    build:
      context: ./front-end
      dockerfile: dockerfile
    ports:
      - "4100:4100"
    volumes:
      - frontend-volume:/app

  backend-service:
    build:
      context: ./back-end 
      dockerfile: dockerfile
    ports:
      - "8080:50"
    volumes:
      - backend-volume:/app

volumes:
  frontend-volume:
  backend-volume:
